[Modem]
# The serial port your RockREMOTE is connected to 
# (e.g., /dev/ttyUSB0 on SBCs, or COM3 on Windows)
Port = /dev/ttyS1

# The communication speed of the serial interface
Baudrate = 115200

# The default RAW IMT Topic ID provisioned for your device
DefaultTopic = 244


[Directories]
# Where incoming messages from the satellite are saved
InboxDir = inbox

# Where your edge applications drop files to be sent
OutboxDir = outbox

# Where successfully transmitted files are archived
SentDir = sent

# Where pruned/expired volatile files (.v) are moved
UnsentDir = unsent


[Limits]
# The maximum number of files to process in a single script run
MaxFilesPerSync = 5

# The maximum size (in bytes) to read from a file. 
# 100000 bytes (100 kB) is the maximum allowed for AT+IMTWU (Binary).
# If you send Text files (AT+IMTWT), the modem limit is 5000 bytes (5 kB).
MaxMessageLength = 100000
